title: CoreELEC - Just enough OS for KODI
author: CoreELEC
description: >-
  CoreELEC is a 'Just enough OS' Linux distribution for running a Media
  Entertainment Center on popular hardware. CoreELEC is a fork of
  LibreELEC project with a stronger focus on community and liberty.
github_username: CoreELEC
theme: minima
